### ISSUE TITLE
Cannot open on MacOS due to "unsafe use of relative rpath ... with restricted binary"

### ISSUE THREAD

**Issue by greglund** [Homebrew/homebrew-cask-drivers#1583]
Process:               Ozone [83167]
Path:                  /Applications/SEGGER/*/Ozone.app/Contents/MacOS/Ozone
Identifier:            com.yourcompany.Ozone
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Ozone [83167]
User ID:               161025775

Date/Time:             2020-05-20 11:32:46.511 -0600
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Bridge OS Version:     3.0 (14Y906)
Anonymous UUID:        E5A75A29-7DE5-481E-64BF-8D5D2901D2FC

Sleep/Wake UUID:       64841C0C-D1F1-49CC-AB4C-0F37FCA28C52

Time Awake Since Boot: 1000000 seconds
Time Since Wake:       99000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
Output/Release/x86_64/libjlinkarm.6.72.2.dylib

Dyld Error Message:
  Library not loaded: */libjlinkarm.6.72.2.dylib
  Referenced from: /Applications/SEGGER/*/Ozone.app/Contents/MacOS/Ozone
  Reason: unsafe use of relative rpath */libjlinkarm.6.72.2.dylib in /Applications/SEGGER/*/Ozone.app/Contents/MacOS/Ozone with restricted binary

Binary Images:
       0x1073ec000 -        0x107b85fff +com.yourcompany.Ozone (???) <60BC030B-62A5-3572-8313-0AED3AE69769> /Applications/SEGGER/*/Ozone.app/Contents/MacOS/Ozone
       0x13fb0b000 -        0x13fb7570f  dyld (655.1.1) <DFC3C4AF-6F97-3B34-B18D-7DCB23F2A83A> /usr/lib/dyld

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by greglund** [comment]
It's okay.  I installed it from the segger site with no issues.  May as well remove the cask if you don't want to fix it

**Comment by vitorgalvao** [comment]
> May as well remove the cask if you don't want to fix it

* Just because something doesn’t work for you, it doesn’t mean it’s broken for everyone else.
* No one said we don’t want to fix the cask, but we can’t look into it without information. Which you haven’t provided.
* You haven’t indicated which cask you’re referring to. We shouldn’t have to hunt it down from a bad bug report that isn’t even formatted as code.
* Your problem seems to be happening after the installation and you’ve opened the app, which makes it way more likely the issue isn’t with Homebrew.
* You‘ve ignored our request for information twice, then were snarky about it. It seems it is you who isn’t interested in helping us fix it.

If this truly is problematic, I’m confident someone else will submit a correct bug report or a fix. If it’s not problematic or no one uses the cask, then no harm done either way.
